workflows:
  android-release:
    name: Android APK Build
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release --android-skip-build-dependency-validation
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - pisiseoo@gmail.com
        notify:
          success: true
          failure: true
